packages:
  - ./
  - playground/
patchedDependencies:
  "@nuxt/module-builder": patches/@nuxt__module-builder.patch
allowUnusedPatches: true
settings:
  cleanupUnusedCatalogs: false
  catalogMode: strict
catalog:
  "@alanscodelog/eslint-config": ^6.3.0
  "@alanscodelog/semantic-release-config": ^5.0.4
  "@alanscodelog/tsconfigs": ^6.2.0
  "@alanscodelog/utils": ^6.0.1
  "@commitlint/cli": ^19.8.1
  "@nuxt/eslint-config": ^1.9.0
  "@nuxt/kit": ^4.1.1
  "@nuxt/module-builder": ^1.0.2
  "@nuxt/schema": ^4.1.1
  "@nuxt/test-utils": ^3.19.2
  change-case: ^5.4.4
  changelogen: ^0.6.2
  defu: ^6.1.4
  eslint: ^9.35.0
  fast-glob: ^3.3.3
  husky: ^9.1.7
  nuxt: ^4.1.1
  typescript: ^5.9.2
  vitest: ^3.2.4
  vue-tsc: ^3.0.6
